import Head from "next/head";
import Movies from "../components/movies/Movies";

export default function Home({ initialMovies }) {
  return (
    <div>
      <Head>
        <title>Ryan&apos;s List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Movies initialMovies={initialMovies} />
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch(
    `https://imdb-api.com/en/API/MostPopularMovies/${process.env.NEXT_PUBLIC_IMDB_KEY}`
  );
  const data = await res.json();
  const totalNumberPages = Math.ceil(data.items.length / 8);
  const moviePages = {};
  const pageIndex = [];
  let i = 1;
  let j = 0;
  while (i <= totalNumberPages) {
    const page = [];
    data.items.forEach((movie, index) => {
      if (index >= j && index < j + 8) {
        page.push(movie);
      }
    });
    moviePages[i] = page;
    pageIndex.push(i);
    j += 8;
    i++;
  }
  return {
    props: {
      initialMovies: { totalNumberPages, moviePages, pageIndex },
    },
  };
};
