import Head from "next/head";
import NewMovies from "../components/newmovies/NewMovies";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ryan&apos;s List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NewMovies />
    </div>
  );
}
